### ISSUE TITLE
Replace gifs with movies?

### ISSUE THREAD

**Issue by hadley** [ismayc/rbasics-book#3]
It would be handy to be able to pause, replay etc.

**Comment by ismayc** [comment]
Agreed. There’s a lot about this book that I’d like to revamp actually.

**Comment by ismayc** [comment]
Just realized a good temporary solution is to convert the GIFs to MP4s, upload them to YouTube and use `vembedr` to host them in the book. It has been done: https://rbasics.netlify.com. Thanks for the suggestion!
