### ISSUE TITLE
Getting Used to R, RStudio, and R Markdown section 4.3

### ISSUE THREAD

**Issue by shrishrineeraj** [ismayc/rbasics-book#8]
Hello,

In your book (online version) "Getting Used to R, RStudio, and R Markdown,"
Under section:
**4.3 R Markdown Chunk Options** 
Reference screenshot attached,

->But when include=FALSE, I see the output in the document.

In the YouTube video (Common R chunk options - Part 2) at 00:25 seconds [Link is here](https://www.youtube.com/watch?v=46N738U3q7k&t=53s) it shows that `include=FALSE` and the output is achieved.

Can you please advise on this, if possible?

![Include False](https://github.com/user-attachments/assets/fc9d3d70-9e68-48f8-92df-2766f7ce28cf)

**Comment by ismayc** [comment]
When you set `include = FALSE` on an R chunk, the code inside the chunk is executed, but neither the code itself nor its immediate output is displayed in the document. This means that any objects created or modified within that chunk are still available for use in later chunks or inline references like what is done in the video.

Therefore, you can still reference objects declared in an `include = FALSE` chunk in the document or other chunks, and they will work as expected. The chunk’s content just won't be visible in the final rendered output.
