### ISSUE TITLE
Some mismatch

### ISSUE THREAD

**Issue by shrishrineeraj** [ismayc/rbasics-book#9]
Sorry to bother again. I really love your book so again here...

Under section:
5.5.2 Using [ , ] with a data frame (online book ->[Link is here](https://rbasics.netlify.app/5-rmdanal#using-with-a-data-frame))
The line says:
"Let’s select rows 40 to 50 and columns 1, 2, and 4 from periodic_table:

periodic_table[41:50, c(1, 2, 4)]
    atomic_number symbol

- 41            41     Nb

- 42            42     Mo
----------------------------

**My query** is, if "Let’s select rows 40 to 50..."
then it should be "periodic_table[40:50..."

Is it a typo or am I missing something?

Please advise. Thanks. 

![data frame](https://github.com/user-attachments/assets/728388f3-bcdd-4688-bc7c-ce175729b0ce)

**Comment by ismayc** [comment]
It is indeed a typo. We’ll look into getting this fixed when we get a chance.

**Comment by ismayc** [comment]
The book has been updated at https://rbasics.netlify.app. Please tag me with @ismayc in a GitHub issue if you identify any other issues that need addressing. Thanks again!
